spring:
  mail:
    host: smtp.163.com
    username: 13605954540@163.com
    password: linlin1314520
    default-encoding: UTF-8

  sms:
    username: xxxx
    password: xxxx
    url: http://xx.xx.xx.xx:8086/xx/xx.asmx/