spring:
  application:
    name: spring-cloud-provider
  kafka:
    bootstrap-servers: 192.168.2.22:9092
    producer:
      acks: all
    consumer:
      group-id: node1-group #三个服务分别为node1 node2 node3
      enable-auto-commit: false

server:
  port: 30001

dubbo:
  registry:
    address: spring-cloud://localhost:8848
  protocol:
    name: "dubbo"
    # 开启dubbo端口自动分配功能, 将从28800开始检索
    port: "-1"
    accesslog: "true"
    threadpool: "cached"
    threads: "500"
  provider:
    delay: "-1"
    timeout: "5000"
  consumer:
    check: "false"
    timeout: "5000"
    init: "true"
    # 关闭重试
    retries: "0"
  application:
    # 关闭QOS特性
    qosEnable: "false"
#  metadata-report:
#    address: spring-cloud://localhost:8848
