dubbo:
  registry:
    address: "zookeeper://127.0.0.1:2181"
  protocol:
    name: "dubbo"
    port: "-1"
    threadpool: "cached"
    threads: "100"
  provider:
    delay: "-1"
    timeout: "10000"
  consumer:
    check: "false"
    timeout: "5000"
    init: "true"
  scan:
    basePackages: com.lp.first.basic.*.provider

